services:
  - type: web
    name: metaphor-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8345263409:AAHF6xusWd8nNaXRryVCvgaft2L8sTbqCVc